# PY_VER=3.8 IMAGE=djbase DISTRO=alpine PHARUS_VERSION=$(cat pharus/version.py | tail -1 | awk -F\" '{print $2}') HOST_UID=$(id -u) docker-compose -f docker-compose-build.yaml up --exit-code-from pharus --build
#
# Intended for updating dependencies and docker image.
# Used to build release artifacts.
version: "2.4"
services:
  pharus:
    build:
      context: .
      args:
        - PY_VER
        - DISTRO
        - IMAGE
    image: jverswijver/pharus:0.5.1-prerelease
    environment:
      - PHARUS_PRIVATE_KEY
      - PHARUS_PUBLIC_KEY
    user: ${HOST_UID}:anaconda
    volumes:
      - .:/main
    command:
      - sh
      - -lc
      - |
        set -e
        rm -R build dist *.egg-info || echo "No prev build"
        python setup.py bdist_wheel sdist
